name       : libbonoboui
version    : 2.24.5
release    : 7
source     :
    - https://download.gnome.org/sources/libbonoboui/2.24/libbonoboui-2.24.5.tar.bz2 : fab5f2ac6c842d949861c07cb520afe5bee3dce55805151ce9cd01be0ec46fcd
license    :
    - GPL-2.0-only
    - LGPL-2.1-only
component  : programming.library
summary    : User Interface library for Bonobo
description: |
    User Interface library for Bonobo
builddeps  :
    - pkgconfig(libglade-2.0)
    - pkgconfig(libgnome-2.0)
    - pkgconfig(libgnomecanvas-2.0)
    - pkgconfig(popt)
    - intltool
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
    rm -rf $installdir/usr/share/applications
